### ISSUE TITLE
[Feature Request] Ability to set polling intervals on a per-hook basis

### ISSUE THREAD

**Issue by JayWelsh** [TrueFiEng/useDApp#530]
This feature request is inspired by the following Twitter thread:

https://twitter.com/nicksdjohnson/status/1491513200797491203

Screenshot:

<img width="594" alt="Screenshot 2022-02-10 at 00 31 56" src="https://user-images.githubusercontent.com/14224459/153301510-d09f3e32-b32d-44e4-9d87-cee9b68d817b.png">

It would be great to be able to override the default DappProvider config polling interval on a per-hook basis when desired, I'm not sure what the best way would be to go about this but thought I'd open the discussion here in case anyone has any thoughts. 🌈

**Comment by dmaretskyi** [comment]
I see this is a widely requested feature. Right now useDapp queries for new blocks periodically (based on provider's own polling) interval and then re-runs all queries on every block.

We a planning to add an ability to disable auto-refresh on per-hook basis. This would be usefull for querying immutable things like names of ERC20 tokens and etc.

I'm not exactly sure yet of how polling interval could work on per-hook basis, since they operate based on blocks rather then time elapsed. Perhaps configuring something like: "re-run this query on every block but only if X seconds have passed since the last run".

Feel free to share more feedback and ideas!

**Comment by RongxinZhang** [comment]
Agreed. I think this would be very useful. 
1. Essentially, what I think would be good is to just be a single call to the chain. 
2. Another option is to provide some sort of caching where someone can specify a state is immutable and this value will be stored in local state somewhere and only polled when it's not founed

**Comment by vm06007** [comment]
hopefully coming soon...

**Comment by mj426382** [comment]
This feature is live now!
https://usedapp-docs.netlify.app/docs/Guides/Reading/Refresh%20Per%20Blocks
