### ISSUE TITLE
broken dependencies

### ISSUE THREAD

**Issue by dcsan** [TrueFiEng/useDApp#939]
**Describe the bug**
broken dependencies

I had useDapp in my app. I recently had to do a clean install of node_modules and now getting these two missing deps.

        "@usedapp/core": "^1.1.5",

**To Reproduce**
install

![image](https://user-images.githubusercontent.com/514002/185715063-768dceac-2bb3-4246-ada6-0fca065ec395.png)

**Software versions**
-        "@usedapp/core": "^1.1.5",
- using npm 
 - node 16

**Additional context**

- Add any other context about the problem here
- Include screenshoots if applicable

haven't touched the code for months, so something environment related, or the shifting sands of npm packages changed underfoot.

**Comment by rzadp** [comment]
Hey @dcsan,

We have marked `useLocalStorage` and some other modules as internal, deprecating its usage, in order to move it out of the public API.

You could still import it explicitly:

```typescript
import { useLocalStorage } from '@usedapp/core/dist/esm/src/internal'
// or
import { useLocalStorage } from '@usedapp/core/dist/cjs/src/internal'
```

Or you could copy the actual code (it is very short).

Seems like you have upgrade usedapp changing a lot of versions. What was your usage of `useInjectedNetwork`? There is now `activateBrowserWallet` in `useEthers` to connect to a wallet, which detects injected provider automatically.

**Comment by dcsan** [comment]
thanks for the response! I didn't write the code, not quite sure what we were using it for.
