### ISSUE TITLE
Docs: Error deploying multicall contract

### ISSUE THREAD

**Issue by alexbakers** [TrueFiEng/useDApp#940]
Hello friends.

How to add multicall to localhost?

<img width="944" alt="image" src="https://user-images.githubusercontent.com/98721968/185814353-8b7346fa-b4a9-4709-8b2c-2bb9d73fb957.png">

<img width="924" alt="image" src="https://user-images.githubusercontent.com/98721968/185814366-38c6fdda-2dae-4efa-ae96-ed39f6464197.png">

<img width="931" alt="image" src="https://user-images.githubusercontent.com/98721968/185814379-008e068c-5517-4f89-aafa-9c7d2ce54724.png">

<img width="921" alt="image" src="https://user-images.githubusercontent.com/98721968/185814396-341605f0-828b-4e71-ba63-43c6bde4a468.png">
 
But the ether balance on the page is **not displayed**.

After update page, againe:

<img width="34" alt="image" src="https://user-images.githubusercontent.com/98721968/185814456-f6092297-56d4-436d-a8ad-4ce1e53c13c6.png">

**Comment by rzadp** [comment]
Hey @alexbakers 

We're narrowing down supported chains in the docs in order to:
1. Keep the examples short
2. Keep the testing surface small

Probably not what you were looking for, but I made it explicit to show what we support in the docs:

![Screenshot 2022-08-23 at 11 38 19](https://user-images.githubusercontent.com/12039224/186128603-97437f33-ff24-417c-a576-fbbe5e9b8237.png)

---

But, the examples are made for copying - so what you could do is:
1. Create an app with useDapp
2. Copy the example
3. Add `[Localhost.chainId]: 'http://localhost:8545'`
4. Run the app and interact with the page

Sorry for the inconvinience!
