### ISSUE TITLE
useDapp is calling provider urls automatically and spiking up the request limit

### ISSUE THREAD

**Issue by ashrhmn** [TrueFiEng/useDApp#944]
**Doing Multiple Request automatically to the readonlyUrls passed in the config**

**To Reproduce**

`
const config: DAppProviderProps["config"] = {
    readOnlyUrls: RPC_URLS
  };
`
Here RPC_URLS is of type `{ [chainId: number]: string }` with all the RPC URLs.

**Software versions**
 - `useDapp` version (installed version of `@usedapp/core`) : 1.0.15
 - Package manager (yarn, npm, or pnpm?) : yarn
 - Node version (`node --version`) : 16.15.0

**Additional context**

I am being rate limited on my infura.io account for doing more than 100k requests a day.  I checked the dashboard about what were the requests and found these.

![image](https://user-images.githubusercontent.com/43120823/186149565-8767245e-bc52-411e-a6c7-08145e4135dd.png)

As I am not doing these requests manually, is the useDapp module sending requests at this rate automatically?

![image](https://user-images.githubusercontent.com/43120823/186150083-3cebcb44-5ada-4b67-8a62-a6efddc0181b.png)

As you can see, networks other than rinkeby was also used to request to the provider but I was doing the dev testing using only rinkeby. So, why are these requests spiking up automatically?

**Comment by rzadp** [comment]
Hey @ashrhmn.

useDApp is automatically quering for block number, and quering for new state for every new block, in order to keep the state up-to-date.

You can configure this behaviour using `refresh` in your useDApp config, to make the requests less frequently, for example every 5 blocks.

However, the amount of calls to `eth_chainId` is wrong - in version `1.0.8`, we made some changes to address this, but apparently they still exist. We should not continiously query for the chain Id that is known.

There is something weird, because on an example app, I reproduced the reporting in Infura with a lot of `eth_chainid` calls, BUT - I do not see them in browser devtools network inspector, just at the beginning which is expected.

**Comment by rzadp** [comment]
I took another whack at it yesterday and today.

So it does not seem like I have a large number of `eth_chainid` calls - just 1-3 at the beginning, and none later (which is the expected behaviour).

![Screenshot 2022-08-26 at 10 38 02](https://user-images.githubusercontent.com/12039224/186860867-0cff36d5-111a-4e63-8801-6ee605b406d0.png)

So @ashrhmn there must be something wrong with your setup, that it racks up so many `eth_chainid` calls. Is your list of `readOnlyUrls` a list of strings? [Internally](https://github.com/TrueFiEng/useDApp/blob/87b6249e795c4241b089f51e6b6eea90dcb7885a/packages/core/src/providers/network/readonlyNetworks/provider.tsx#L27) it will create a `StaticJsonRpcProvider` which knows not to query for chainId - this is since useDapp 1.0.8 I think.

---

As for other networks - do you not have any hooks using the other chains? It might be just requests to keep the block number up-to-date.

**Comment by rzadp** [comment]
@ashrhmn Ok looks good

> I am being rate limited on my infura.io account for doing more than 100k requests a day. I checked the dashboard about what were the requests and found these.

So what kind of usage do you have? Do you have the app deployed and used?
Also I see some (faling) requests for `net_version` - That I don't think comes from useDApp.

**Comment by ashrhmn** [comment]
I previously had the useDapp hooks set up, but after the issue, I switched to this approach for fetching. Still, the problem is not fixed. Is there anything wrong with `getDefaultProvider`?

```js

  useEffect(() => {
    try {
      (async () => {
        if (!projectAddress || !projectChainId || !RPC_URLS[projectChainId])
          return;
        const contract =
          collectionType === "721"
            ? Collection721__factory.connect(
                projectAddress,
                getDefaultProvider(RPC_URLS[projectChainId])
              )
            : Collection1155__factory.connect(
                projectAddress,
                getDefaultProvider(RPC_URLS[projectChainId])
              );
        setFeeAddressBgProc((v) => v + 1);
        setMaxMintInTotalPerWalletBgProc((v) => v + 1);
        setBaseURIBgProc((v) => v + 1);
        const [
          feeToAddress,
          baseURI,
          maxMintInTotalPerWallet,
          revealTime,
        ] = await Promise.all([
          contract.feeDestination().catch((e) => {
            console.log("Error getting feeDestination  : ", e);
            return "";
          }),
          contract.baseURI().catch((e) => {
            console.log("Error getting baseURI  : ", e);
            return "";
          }),
          contract.maxMintInTotalPerWallet().catch((e) => {
            console.log("Error getting maxMintInTotalPerWallet : ", e);
            return 0;
          }),
          contract.revealTime().catch((e) => {
            console.log("Error getting revealTime  : ", e);
            return BigNumber.from(0);
          }),
        ]);

        setConfigSet((c) => ({
          ...c,
          feeToAddress,
          baseURI,
          maxMintInTotalPerWallet: +maxMintInTotalPerWallet.toString(),
          revealTime: revealTime.toNumber(),
        }));
        setFeeAddressBgProc((v) => v - 1);
        setBaseURIBgProc((v) => v - 1);
        setMaxMintInTotalPerWalletBgProc((v) => v - 1);
      })();
    } catch (error) {
      setMaxMintInTotalPerWalletBgProc((v) => v - 1);
      setBaseURIBgProc((v) => v - 1);
      setFeeAddressBgProc((v) => v - 1);
      console.log("Error fetching : ", error);
    }
  }, [collectionType, projectAddress, projectChainId]);

```

**Comment by rzadp** [comment]
@ashrhmn It might be.
Instead, try:
```
import { providers } from 'ethers'
const { StaticJsonRpcProvider } = providers

new StaticJsonRpcProvider(RPC_URLS[projectChainId])
```

**Comment by ashrhmn** [comment]
I tested for a day. Using StaticJsonRpcProvider drastically reduced network calls. The last 24h reporting says a total of around 5k calls to the API. 

<img width="1534" alt="image" src="https://user-images.githubusercontent.com/43120823/187051242-ced29e51-2519-4047-bd44-1c37125a9ef9.png">

Still, I am having a lot of chainId requests but that is negligible I guess.
